# syntax=docker/dockerfile:1
# Build stage
FROM golang:1.21-alpine3.19 AS builder

# Instalar dependencias necesarias
RUN apk add --no-cache gcc musl-dev sqlite-dev

# Establecer el directorio de kerja
WORKDIR /app

# Copiar archivos de dependencias para caching
COPY apps/monitoring/go.mod apps/monitoring/go.sum ./apps/monitoring/

# Movernos al direktori aplikasi
WORKDIR /app/apps/monitoring

# Descargar dependencias
RUN go mod download

# Kembali ke root dan salin sisa kode
WORKDIR /app
COPY . .

# Compilar la aplikasi
WORKDIR /app/apps/monitoring
RUN CGO_ENABLED=1 GOOS=linux go build -o main main.go

# Etapa final
FROM alpine:3.19

# Instalar SQLite y otras dependencias necesarias
RUN apk add --no-cache sqlite-libs docker-cli

WORKDIR /app

# Copiar el binario compilado y el archivo monitor.go
COPY --from=builder /app/apps/monitoring/main ./main
COPY --from=builder /app/apps/monitoring/main.go ./monitor.go

# COPY --from=builder /app/apps/golang/.env ./.env

# Exponer el puerto
ENV PORT=3001
EXPOSE 3001

# Ejecutar la aplicación
CMD ["./main"]